.TH zsurf 1 "2017-3-1" "zero surf" "User Commands"
.\" --------------------------------------------------------------------
.SH NAME
zsurf \- basic webkit2gtk browser
.\" --------------------------------------------------------------------
.SH DESCRIPTION
\fBzsurf\fP is a simple web browser, using GTK+ 3 and WebKit2GTK+.
.\" --------------------------------------------------------------------

.SH SHORTCUTS

For actual list of shortcuts/keys refer to page of project http://github.com/SteveDeFacto/zsurf
.\" --------------------------------------------------------------------

.SH FILES
Files created in your home dir:
.TP
 .zsurf - directory for cookies, cached content, and bookmarks.
.TP
 .local/share/webkitgtk/* - directories for local storage and databases.
.\" --------------------------------------------------------------------
.SH LICENSE
\fBzsurf\fP is on GPL license.
